# Generated by Django 4.0.3 on 2022-04-18 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doggieHommie', '0006_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functionality',
            options={'verbose_name': 'funcionalidad', 'verbose_name_plural': 'funcionalidades'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'rol', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='veterinary',
            options={'verbose_name': 'Veterinario', 'verbose_name_plural': 'Veterinarios'},
        ),
        migrations.AlterModelOptions(
            name='veterinary_files',
            options={'verbose_name': 'archivo_vet', 'verbose_name_plural': 'archivos_vet'},
        ),
    ]
