# Generated by Django 3.1.2 on 2022-04-10 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doggieHommie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_graduacion', models.DateField()),
                ('universidad', models.CharField(max_length=60)),
                ('fecha_registro', models.DateField()),
                ('calificacion', models.FloatField()),
                ('numero_tarjeta_profesional', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='correo_electronico',
            field=models.EmailField(max_length=50),
        ),
        migrations.CreateModel(
            name='Veterinary_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('extension', models.CharField(max_length=60)),
                ('archivo', models.CharField(max_length=1000)),
                ('veterinary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doggieHommie.veterinary')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=90)),
                ('veterinaries', models.ManyToManyField(blank=True, to='doggieHommie.Veterinary')),
            ],
        ),
    ]
