# Generated by Django 3.1.2 on 2022-04-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggieHommie', '0002_auto_20220410_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=100)),
                ('veterinaries', models.ManyToManyField(blank=True, to='doggieHommie.Veterinary')),
            ],
        ),
        migrations.CreateModel(
            name='Functionality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('url', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=100)),
                ('rol', models.ManyToManyField(blank=True, to='doggieHommie.Rol')),
            ],
        ),
    ]
