# Generated by Django 4.0.3 on 2022-04-18 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doggieHommie', '0005_alter_functionality_id_alter_rol_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='primer_apellido',
            new_name='second_lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='primer_nombre',
            new_name='second_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contrasenia',
        ),
        migrations.RemoveField(
            model_name='user',
            name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='user',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='user',
            name='segundo_nombre',
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to=settings.AUTH_USER_MODEL),
        ),
    ]
