# Generated by Django 4.0.3 on 2022-04-20 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doggieHommie', '0007_alter_functionality_options_alter_rol_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinary',
            name='associated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doggieHommie.user'),
        ),
    ]
