# Generated by Django 4.0.3 on 2022-04-25 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doggieHommie', '0008_veterinary_associated_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='user',
            name='second_lastname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tipo_documento',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('grade', models.IntegerField()),
                ('isDonation', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doggieHommie.user')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('extension', models.CharField(max_length=10)),
                ('file', models.ImageField(upload_to='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doggieHommie.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doggieHommie.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doggieHommie.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doggieHommie.user')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doggieHommie.user')),
            ],
        ),
    ]
