# Generated by Django 4.0.3 on 2022-05-03 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doggieHommie', '0009_remove_user_departamento_remove_user_second_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccounts',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doggieHommie.post'),
        ),
    ]
