# Generated by Django 4.0.3 on 2022-05-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggieHommie', '0010_bankaccounts_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functionality',
            options={},
        ),
        migrations.RemoveField(
            model_name='bankaccounts',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='bankAccounts',
            field=models.ManyToManyField(blank=True, to='doggieHommie.bankaccounts'),
        ),
    ]
