# Generated by Django 4.0.3 on 2022-05-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggieHommie', '0012_bankaccounts_bank_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
