# Generated by Django 4.0.3 on 2022-05-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggieHommie', '0013_post_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_banned',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
