# Generated by Django 4.0.3 on 2022-05-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doggieHommie', '0015_alter_post_number_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
