# Generated by Django 4.0.3 on 2022-05-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggieHommie', '0017_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_banned',
            field=models.IntegerField(null=True),
        ),
    ]
