# Generated by Django 4.0.3 on 2022-05-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggieHommie', '0019_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounts',
            name='bank_name',
            field=models.CharField(choices=[('NQ', 'Nequi'), ('PP', 'Paypal'), ('DP', 'Daviplata')], max_length=120),
        ),
    ]
