# Generated by Django 4.0.3 on 2022-05-30 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doggieHommie', '0022_remove_post_imagess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doggieHommie.image_field')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doggieHommie.post')),
            ],
        ),
    ]
