# Generated by Django 4.0.3 on 2022-06-15 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doggieHommie', '0024_postsliked_alter_functionality_options_post_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='doggieHommie.user'),
        ),    
    ]
