# Generated by Django 4.0.3 on 2022-06-17 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doggieHommie', '0026_postsliked_alter_functionality_options_post_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doggieHommie.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doggieHommie.user')),
            ],
        ),
    ]
